Citizen.CreateThread(function()
	AddTextEntry("unmarkbuff", "Buffalo Banalisé")
	AddTextEntry("unmarkora", "Oracle Banalisé")
	AddTextEntry("unmarksult", "Sultan Banalisé")
	AddTextEntry("sanchezbcso", "Sanchez BCSO")
	AddTextEntry("umkspeedo", "Speedo Banalisé")
	AddTextEntry("supra2", "Toyota Supra JZA80")
	AddTextEntry("SkylineGTR", "Nissan Skyline GTR R34")
	AddTextEntry("evo9", "Mitsubishi Lancer Evolution IX")
	AddTextEntry("silvias15", "Nissan Silvia S15")
	AddTextEntry("mustgt19", "Ford Mustang 2019")
	AddTextEntry("16charger", "Dodge Charger SRT")
	AddTextEntry("newsvan", "Rumpo Radio")
	AddTextEntry("lsfuel", "Camion Citerne")
	AddTextEntry("landstal", "Landstalker")
	AddTextEntry("LSPDstanier", "LSPD Vapid Stanier 2010")
	AddTextEntry("LSPDoldstanier", "LSPD Vapid Stanier 2000")
	AddTextEntry("LSPDstanierslick", "LSPD Vapid Stanier 2010 Slicktop")
	AddTextEntry("LSPDscout", "LSPD Vapid Scout 2014")
	AddTextEntry("LSPDbuffalo", "LSPD Bravado Buffalo S 2017")
	AddTextEntry("LSPDcontendder", "LSPD Vapid Contender Beach Detail")
	AddTextEntry("LSPDtorrence", "LSPD Vapid Torrence 2015")
	AddTextEntry("LSPDtorrenceslick", "LSPD Vapid Torrence 2015 Slicktop")
	AddTextEntry("LSPDsovereign", "LSPD WMC Sovereign 1998")
	AddTextEntry("LSPDumkstanier", "Vapid Stanier 2010 UMK")
	AddTextEntry("LSPDumktorrence", "LSPD Vapid Torrence 2015 UMK")
	AddTextEntry("LSPDumkbuffalo", "Bravado Buffalo S Unmarked")
	AddTextEntry("LSPDumkmerit", "Declasse Merit Unmarked")
	AddTextEntry("LSPDumkscout", "Vapid Scout 2014 Unmarked")
	AddTextEntry("LSPDbuff10", "LSPD Bravado Buffalo 2010")
	AddTextEntry("LSPDalamo", "LSPD Declasse Alamo")
	AddTextEntry("LSPDoldgrang", "LSPD Declasse Granger 1997")
	AddTextEntry("LSSDbuff10", "LSSD Bravado Buffalo 2010")
	AddTextEntry("LSSDriata", "LSSD Vapid Riata")
	AddTextEntry("LSSDcoquette", "LSSD Coquette MRD")
	AddTextEntry("LSSDfugitive", "LSSD Cheval Fugitive")
	AddTextEntry("LSSDgranger", "LSSD Declasse Granger")
	AddTextEntry("LSSDinsurgent", "LSSD Insurgent SET")
	AddTextEntry("LSSDstanier", "LSSD Vapid Stanier 2010")
	AddTextEntry("LSSDscout", "LSSD Vapid Scout 2014")
	AddTextEntry("LSSDalamo", "Declasse Alamo LSSD")
	AddTextEntry("LSSDenduro", "Dinka Enduro LSSD")
	AddTextEntry("LSSDlandroamer", "Dundreary Landroamer LSSD")
	AddTextEntry("LSSDlandstalker", "Dundreary Landstalker LSSD")
	AddTextEntry("LSSDrumpo", "Bravado Rumpo LSSD")
	AddTextEntry("LSSDscout", "Vapid Scout 2014 LSSD")
	AddTextEntry("LSSDscout2", "Vapid Scout 2016 LSSD")
	AddTextEntry("LSSDseashark", "Speedophile Seashark LSSD")
	AddTextEntry("LSSDstanierslick", "Vapid Stanier Slicktop LSSD")
	AddTextEntry("LSSDthrust", "Dinka Thrust LSSD")
	AddTextEntry("LSPDraiden", "LSPD Coil Raiden MRD")
	AddTextEntry("K9scout", "LSPD K9 Scout 2014")
	AddTextEntry("K9stanier", "LSPD K9 Stanier 2010")
	AddTextEntry("LSPDmav", "Maverick LSSD LSPD EMS")
	AddTextEntry("polTARV", "Vapid TARV")
	AddTextEntry("LSPDriot", "LSPD Riot")
	AddTextEntry("LSPDspeedo", "LSPD Vapid Speedo")
	AddTextEntry("umkbuff10", "Bravado Buffalo 2010 Unmarked")
	AddTextEntry("umkgranger", "Granger Unmarked")
	AddTextEntry("poldinghy", "Police Dinghy")
	AddTextEntry("polpreda", "Police Predator")
	AddTextEntry("LSFDamb", "Vapid V450 Ambulance LSFD/BCFD")
	AddTextEntry("LSFDamb2", "Vapid Landstalker Ambulance LSFD/BCFD")
	AddTextEntry("LSFDamb3", "Bravado Bison Ambulance LSFD/BCFD")
	AddTextEntry("LSFDamb4", "Bravado Rumpo Ambulance LSFD/BCFD")
	AddTextEntry("LSFDfugitif", "Cheval Fugitive LSFD/BCFD")
	AddTextEntry("LSFDgrang", "Declasse Granger LSFD/BCFD")
	AddTextEntry("LSFDlandstalker", "Dundreary Landstalker LSFD/BCFD")
	AddTextEntry("LSFDstanier", "Vapid Stanier 2010 LSFD/BCFD")
	AddTextEntry("LSFDstanier2", "Vapid Stanier LSFD/BCFD")
	AddTextEntry("LSFDtruck", "MTL Engine")
	AddTextEntry("LSFDtruckhazard", "MTL Hazard Truck")
	AddTextEntry("LSFDtruckold", "MTL Utility Truck")
	AddTextEntry("LSFDutil", "Bravado Utility LSFD/BCFD")
	AddTextEntry("LSFDwaterres", "Vapid Sadler Water Rescue LSFD/BCFD")
	AddTextEntry("BCFDannihilator", "Western Annihilator BCFD")
	AddTextEntry("BCFDblazer", "Nagasaki Blazer BCFD")
	AddTextEntry("BCFDseashark", "Speedophile Seashark BCFD")
	AddTextEntry("Lalamo", "Declasse Alamo Lifeguard")
	AddTextEntry("Lcontender", "Vapid Contender Lifeguard")
	AddTextEntry("Leveron", "Karin Everon Lifeguard")
	AddTextEntry("Lfreecrawler", "Freecrawler Lifeguard")
	AddTextEntry("Lgranger", "Declasse Granger Lifeguard")
	AddTextEntry("Lmesa", "Canis Mesa Lifeguard")
	AddTextEntry("Lriata", "Vapid Riata Lifeguard")
	AddTextEntry("Lsandking", "Vapid Sandking Lifeguard")
	AddTextEntry("Lspeedo", "Vapid Speedo Lifeguard")
	AddTextEntry("Lsqualo", "Shitzu Squalo Lifeguard LS")
	AddTextEntry("LsqualoBC", "Shitzu Squalo Lifeguard BC")
	AddTextEntry("Lsteed", "Vapid Steed Lifeguard")
	AddTextEntry("Lverus", "Dinka Verus Lifeguard")
	AddTextEntry("Lutillitruck", "Utility Truck Lifeguard")
	AddTextEntry("Lyosemite", "Lifeguard Declasse Yosemite")
	AddTextEntry("newsmav", "Maverick Weazel News")
	AddTextEntry("RANGERgranger", "Ranger Declass Granger")
	AddTextEntry("RANGERseminole", "Ranger Seminole")
	AddTextEntry("RANGERvolito", "Ranger SuperVolito")
	AddTextEntry("RANGERpredator", "Ranger Predator")
	AddTextEntry("RANGERscout", "Ranger Vapid Scout")
	AddTextEntry("RANGERtorrence", "Ranger Vapid Torrence")
	AddTextEntry("RANGERpatriot", "Ranger Patriot")
	AddTextEntry("RANGERsadler", "Ranger Vapid Sadler")
	AddTextEntry("RANGERutil", "Ranger Utility Truck")
	AddTextEntry("RANGERstanier", "Ranger Vapid Stanier")
	AddTextEntry("RANGERriata", "Ranger Vapid Riata")
	AddTextEntry("RANGERlandroamer", "Ranger Landroamer")
	AddTextEntry("RANGERbison", "Ranger Bison")
	AddTextEntry("RANGERoutlaw", "Ranger Outlaw")
	AddTextEntry("RANGERfreecrawler", "Ranger Freecrawler")
	AddTextEntry("RANGERyosemite2", "Ranger Declasse Yosemite")
	AddTextEntry("RANGERyosemite2", "Ranger Yosemite Rancher")
	AddTextEntry("RANGERmesa", "Ranger Mesa")
	AddTextEntry("RANGERalamo", "Ranger Declasse Alamo")
	AddTextEntry("RANGERalamok9", "Ranger Declasse Alamo K9")
	AddTextEntry("RANGERyosemitek9", "Ranger Yosemite K9")
	AddTextEntry("RANGERlandroamerk9", "Ranger Landroamer K9")
	AddTextEntry("USSSgrangerbar", "USSS Declasse Granger Lightbar")
	AddTextEntry("USSSgranger", "USSS Declasse Granger")
	AddTextEntry("USSSvip", "USSS Declasse Granger VIP")
	AddTextEntry("USSShazard", "USSS Vapid Hazard Ambulance")
	AddTextEntry("USSSvan", "USSS Bravado Rumpo")
end)